<?php
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
?><?php
	$APPLICATION->IncludeComponent(
	'marso.test.news',
	'',
    [],
	false
);?><?php
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');